#+title: organ

[[https://intver.org/][https://img.shields.io/badge/versioning-intver.org-blue.svg?style=for-the-badge]]

A Clojure library to parse [[https://orgmode.org][Org mode]] text into an AST (EDN data).

* Usage

#+begin_src clojure
(require '[bzg.organ :as organ])

(organ/parse-org "* Hello\nSome *bold* text")
;; => {:type :document, :title "Untitled Document",
;;     :todo-keywords {:todo ["TODO"], :done ["DONE"]}, :children [...]}

(organ/format-ast-as-edn (organ/parse-org (slurp "notes.org")))
#+end_src

Text fields in the AST preserve raw Org markup. Rendering is left to
consumers (see [[https://github.com/bzg/hop][hop]]).

TODO keywords: headlines are matched against =TODO= and =DONE= by
default. =#+TODO:=, =#+SEQ_TODO:= and =#+TYP_TODO:= directives found
anywhere in the file replace this default set for the whole document
(as in Emacs Org, including =|= separators and fast-access selectors
like =TODO(t)=). Keywords coming from your Emacs configuration rather
than from the file can be passed with the =:todo-keywords= option,
which extends the effective set:

#+begin_src clojure
(organ/parse-org org-string {:todo-keywords "NEXT STRT WAIT | CANX"})
;; or {:todo-keywords {:todo ["NEXT"] :done ["CANX"]}}
#+end_src

The effective set is exposed on the document node as =:todo-keywords=
(={:todo [...] :done [...]}=), and =parse-todo-keywords= extracts the
directive-defined set from raw Org text.

Filter and clean:

#+begin_src clojure
(-> (organ/parse-org org-string)
    (organ/filter-ast {:level-limit 2 :title-pattern #"TODO"})
    organ/clean-node)
#+end_src

* Install

As a Clojure CLI dependency:

#+begin_src clojure
org.clojars.bzg/organ {:mvn/version "3.2.0"}
#+end_src

Works with both Clojure and [[https://babashka.org][Babashka]] (no external deps).

* Test

: ~$ bb test

* Deploy

Set your Clojars credentials in the environment:

: export CLOJARS_USERNAME=your-username
: export CLOJARS_PASSWORD=your-deploy-token

Build the jar and deploy:

: clj -T:build deploy

To install locally instead:

: clj -T:build install

To just build the jar without deploying:

: clj -T:build jar

The version is set in =build.clj=.

* Contribute

- Send a [[mailto:~bzg/orgology@lists.sr.ht][bug report]] with =[BUG] organ: <SHORT EXPLICIT BUG DESCRIPTION>=
- Send a [[mailto:~bzg/orgology@lists.sr.ht][patch]] with =[PATCH] organ: <COMMIT SUMMARY>=
- Send a [[mailto:~bzg/orgology@lists.sr.ht][feature request]] with =[FR] organ: <FEATURE REQUEST>=
- Share any [[mailto:~bzg/orgology@lists.sr.ht][other question or idea]]

You can also [[mailto:bzg@bzg.fr][send me an email]] and support my work on [[https://liberapay.com/bzg/][liberapay]].

* Intentional Versioning

This project uses [[https://intver.org][Intentional Versioning]], here are the three audiences:

- =Users= : Maintainers who rely on organ for their code
- =Integrators= : N/A
- =Maintainers= : maintainers of the codebase

* Support the Clojure(script) ecosystem

If you like Clojure(script), please consider supporting maintainers by
donating to [[https://clojuriststogether.org][clojuriststogether.org]].

* License

Copyright © 2026 Bastien Guerry

Distributed under the Eclipse Public License 2.0.
